### ISSUE TITLE
Contribution request

### ISSUE THREAD

**Issue by atageldi194229** [Mickey-A-Mouse/turkmen_localization_support#10]
All developers that want to contribute, please comment here.

**Comment by AtamyratBabayev** [comment]
Hi! I'm very happy that this repository is usefull for you, later I'll post information about how to contribute to this repository.

**Comment by AtamyratBabayev** [comment]
Hi, finally I've find time to update README. All information about contribution you could find there!
Close this and waiting for your contributions!
