### ISSUE TITLE
Static Analysis Failure with lints_core on TkCupertinoLocalization Class

### ISSUE THREAD

**Issue by merdandt** [Mickey-A-Mouse/turkmen_localization_support#11]
**Description**:
When running static analysis using the lints_core package, the TkCupertinoLocalization class fails to pass. This issue might indicate a problem with compliance to updated linting rules or potential errors in the code structure that need attention.

**Steps to Reproduce:**
Ensure the lints_core package is included in your pubspec.yaml and up to date.
Navigate to the root of your Flutter project in the terminal.
Run the following command: flutter analyze lib/src/tk_cupertino_localizations.dart

```
46 │ class TkCupertinoLocalization extends GlobalCupertinoLocalizations {
   │       ^^^^^^^^^^^^^^^^^^^^^^^
  ```
   
**Expected Behavior:**
The code should pass all static analysis checks without any errors.

**Actual Behavior:**
The analyzer highlights an error at the definition of the TkCupertinoLocalization class, suggesting a possible linting violation or syntax issue.

**Environment:**
Flutter version: 3.19.4
Dart version: 3.3.2

**Comment by AtamyratBabayev** [comment]
Hi, I guess there is issue related to intl, I'll update it.
