### ISSUE TITLE
FUTURE VISION of PACKAGE

### ISSUE THREAD

**Issue by atageldi194229** [Mickey-A-Mouse/turkmen_localization_support#15]
Range Naming: If a branch supports a range of versions, you could indicate the range in the branch name. This is useful if the changes between some Flutter versions are minor and do not require separate branches. For example:

  -  flutter-1.20-1.22
  -  flutter-2.0-2.2
  -  etc.

**Comment by AtamyratBabayev** [comment]
> Range Naming: If a branch supports a range of versions, you could indicate the range in the branch name. This is useful if the changes between some Flutter versions are minor and do not require separate branches. For example:
> 
> * flutter-1.20-1.22
> * flutter-2.0-2.2
> * etc.

Hi, thank you for note. I think it's better to write about flutter versioning inside of changelog. Therefore users could see current flutter version in pub.dev without going to repo. This leads to creation of more than one commit, for example chore:upgrade intl, feat: add translations, docs: update changelog etc.
Btw, according to commit convention, there should be new branch for every update.

**Comment by AtamyratBabayev** [comment]
In addition, unfortunately, there is no way to downgrade flutter version. You still could fork it and update it by your needs)

**Comment by AtamyratBabayev** [comment]
Hope, conversation was useful. If no questions, I'll close ot as solved!
